plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
  id 'kotlin-android'
  id 'org.jetbrains.kotlin.android'
  
}

group = 'expo.modules.screenorientation'
version = '0.7.9'

android {
  namespace "expo.modules.screenorientation"
  defaultConfig {
    versionCode 1
    versionName "0.7.9"
  }
  lintOptions {
    abortOnError false
  }
}
